#!/usr/bin/perl
 
use strict;
use warnings;
 
sub trim{
   my $string = shift;
   $string =~ s/^\s+|\s+$//g;
   return $string;
}
 
print "\nQueuing Build\n";
my $revision = trim(`git log --no-merges --format="%H" -1`);
my $author = trim(`git log --no-merges --format="%aN" -1`);
my $commitMessage = trim(`git log --format="%s" --no-merges -1`);

GIT_WORK_TREE=/c/temp/gitbuilddir/

git checkout -f

open(MYFILE, ">>builds/build-$revision.txt");

print MYFILE $revision;
print MYFILE ":::";
print MYFILE "/c/temp/gitbuilddir/";
close (MYFILE);
 
exit 0;